version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 |
        docker login --username AWS --password-stdin 067717894185.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - docker build -t vendor2-ui:latest .
      - docker tag  vendor2-ui:latest 067717894185.dkr.ecr.ap-northeast-1.amazonaws.com/vendor2-ui:latest
  post_build:
    commands:
      - docker push 067717894185.dkr.ecr.ap-northeast-1.amazonaws.com/vendor2-ui:latest
artifacts: { files: [] }
